# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.0.24
_src_path: gh:clearskies-akeyless-custom-producers/template
author_email: cmancone@gmail.com
author_name: Conor Mancone
service_display_name: Wiz
service_name: wiz
service_supports_revocation: false
service_supports_rotation: true
