name: Auto Delete Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    # Only run this job if the PR was merged
    if: github.event.pull_request.merged == true
    steps:
      - name: Delete branch
        uses: srggrs/delete-branch-on-merge@v1.1.0
        with:
          # The GITHUB_TOKEN is automatically provided
          github_token: ${{ secrets.GITHUB_TOKEN }}
